### ISSUE TITLE
Impossible to install app

### ISSUE THREAD

**Issue by dienteperro** [nextcloud/ocsms#169] opened 2017-02-01 23:40 UTC
When trying to enable app constantly says table 'oc_ocsms_smsdatas' has problems. I deleted the table, recreated with the correct settings (TEXT) but then says table 'oc_ocsms_user_datas' already exists. Couldn't enable it in any way. My database was setup at the beginning of the Next cloud install as CREATE DATABASE nextcloud CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci; 

Also mysql server does have the required parameter set:
[mysqld]
innodb_large_prefix=true
innodb_file_format=barracuda
innodb_file_per_table=1

### Steps to reproduce
1. Install the nextcloud server, setup according to the guide creating manually the database prior to deploy.
2. Enable the app Nextcloud SMS
3. The app is unable to install/enable constantly shows errors.

### Expected behaviour
The app should detect if tables exists and set it up accordingly, perhaps is necesary to change the statement for the tables creation.

### Actual behaviour
The app does not install

### Server configuration

**NextCloud/ownCloud version:** 11.0.1 (stable)

**PHP version:** 7.0.13

**HTTPd server:** Apache/2.4.18 (Ubuntu)

**HTTPS:**

**mysql:** 5.7.17

### Client configuration

**Android version:**

**Phone:**

**ownCloud SMS app version:** 1.11.4

### Logs

```
An exception occurred while executing 'CREATE TABLE `oc_ocsms_smsdatas` (`id` BIGINT AUTO_INCREMENT NOT NULL, `user_id` VARCHAR(64) NOT NULL, `added` DATETIME DEFAULT '1970-01-01 00:00:00' NOT NULL, `lastmodified` DATETIME DEFAULT '1970-01-01 00:00:00' NOT NULL, `sms_id` BIGINT NOT NULL, `sms_address` VARCHAR(64) NOT NULL, `sms_msg` VARCHAR(20480) NOT NULL, `sms_date` BIGINT NOT NULL, `sms_flags` VARCHAR(2) DEFAULT '00' NOT NULL, `sms_mailbox` SMALLINT NOT NULL, `sms_type` SMALLINT NOT NULL, INDEX smsdata_user_mailbox (`user_id`, `sms_mailbox`), INDEX smsdata_user_smsid (`user_id`, `sms_id`), INDEX smsdata_user_mailbox_date (`user_id`, `sms_mailbox`, `sms_date`), INDEX smsdata_user_mailbox_address (`user_id`, `sms_mailbox`, `sms_address`), INDEX smsdata_user_mailbox_address_date (`user_id`, `sms_mailbox`, `sms_address`, `sms_date`), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed': SQLSTATE[42000]: Syntax error or access violation: 1074 Column length too big for column 'sms_msg' (max = 16383); use BLOB or TEXT instead

An exception occurred while executing 'CREATE TABLE `oc_ocsms_user_datas` (`user_id` VARCHAR(64) NOT NULL, `datakey` VARCHAR(64) NOT NULL, `datavalue` VARCHAR(64) NOT NULL, INDEX user_datas_user_datakey (`user_id`, `datakey`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed': SQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_ocsms_user_datas' already exists

{"reqId":"nYLwEkE5uvjumpPOn7yd","remoteAddr":"10.10.0.181","app":"core","message":"An exception occurred while executing 'CREATE TABLE `oc_ocsms_user_datas` (`user_id` VARCHAR(64) NOT NULL, `datakey` VARCHAR(64) NOT NULL, `datavalue` VARCHAR(64) NOT NULL, INDEX user_datas_user_datakey (`user_id`, `datakey`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed':\n\nSQLSTATE[42S01]: Base table or view already exists: 1050 Table 'oc_ocsms_user_datas' already exists","level":3,"time":"2017-02-01T23:18:27+00:00","method":"POST","url":"\/index.php\/settings\/ajax\/enableapp.php","user":"user","version":"11.0.1.2"}

{"reqId":"T65koFHfDBaWhdEaxFaJ","remoteAddr":"10.10.0.181","app":"core","message":"An exception occurred while executing 'CREATE TABLE `oc_ocsms_smsdatas` (`id` BIGINT AUTO_INCREMENT NOT NULL, `user_id` VARCHAR(64) NOT NULL, `added` DATETIME DEFAULT '1970-01-01 00:00:00' NOT NULL, `lastmodified` DATETIME DEFAULT '1970-01-01 00:00:00' NOT NULL, `sms_id` BIGINT NOT NULL, `sms_address` VARCHAR(64) NOT NULL, `sms_msg` VARCHAR(20480) NOT NULL, `sms_date` BIGINT NOT NULL, `sms_flags` VARCHAR(2) DEFAULT '00' NOT NULL, `sms_mailbox` SMALLINT NOT NULL, `sms_type` SMALLINT NOT NULL, INDEX smsdata_user_mailbox (`user_id`, `sms_mailbox`), INDEX smsdata_user_smsid (`user_id`, `sms_id`), INDEX smsdata_user_mailbox_date (`user_id`, `sms_mailbox`, `sms_date`), INDEX smsdata_user_mailbox_address (`user_id`, `sms_mailbox`, `sms_address`), INDEX smsdata_user_mailbox_address_date (`user_id`, `sms_mailbox`, `sms_address`, `sms_date`), PRIMARY KEY(`id`)) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin ENGINE = InnoDB ROW_FORMAT = compressed':\n\nSQLSTATE[42000]: Syntax error or access violation: 1074 Column length too big for column 'sms_msg' (max = 16383); use BLOB or TEXT instead","level":3,"time":"2017-02-01T23:20:20+00:00","method":"POST","url":"\/index.php\/settings\/ajax\/enableapp.php","user":"user","version":"11.0.1.2"}
```

**Comment by nerzhul** [comment] 2017-02-03 21:37
Error is already fixed in master, we just need to release. If you want install it shortly please change column side in appinfos/database.xml

**Closed by nerzhul** 2017-02-03 21:37 UTC

**Comment by nerzhul** [comment] 2017-02-03 21:42
I released 1.11.5 now to fix your issues

**Comment by dienteperro** [comment] 2017-02-04 00:07
My test server is fine now, will check on production in a few days! Thanks a lot. I try this proceed:

1. Untar Nextcloud bz2 file.
2. Run the .sh to fix directories perms and ownership
3. Create DB: CREATE DATABASE nextcloud CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;
3.1 GRANT ALL ON nextcloud.* to 'nextcloud'@'localhost' IDENTIFIED BY 'set_database_password';
3.2 FLUSH PRIVILEGES;
4. Install from the web GUI specifying mysql db with previous config
5. Set sudo -u www-data /var/www/nextcloud/occ config:system:set mysql.utf8mb4 --type boolean --value="true"
6. Install apps (I tested External user, External storage, Contacts, Calendar, Phone Sync)
7. sudo -u www-data /var/www/nextcloud/occ maintenance:repair
8. I checked the logs, and everything was fine
9. Setup sync in mobile phone
10. Checked logs again, all okay.
11. login as user with linked phone, SMSs were ther with their emoji ;-)

On Monday will do more testing. Thanks nerzhul, great work.

**Comment by enoch85** [comment] 2017-02-04 10:13
@dienteperro Just a question, why did you do all this manually when really the only thing you have to do is install the app from inside the Nextcloud App store?

**Comment by nerzhul** [comment] 2017-02-04 12:23
no problem, the MySQL shit UTF8 problem was fixed by @enoch85 not me :) i didn't knew UTF8 was bloated on MySQL (and i'm using pgsql)

**Comment by dienteperro** [comment] 2017-02-06 14:05
enoch85 I was trying to figure it out, and remove all and started from scratch in different ways trying to find in which step the problem arises. When I installed the app from the Nextcloud App store, it (the app) notifies me that can't be installed due to errors in the creation of the tables.

**Comment by dienteperro** [comment] 2017-02-06 14:07
nerzhul In my deep feelings I'm considering to use pgsql for my setup, but not totally sure due to lack of support from nextcloud developers. Also considering nginx as a replacement for apache.

**Comment by nerzhul** [comment] 2017-02-06 15:12
i don't know why they doesn't support pgsql as it has a stronger SGBD, unlike mysql (look at this UTF8 crap...)

**Comment by enoch85** [comment] 2017-02-06 15:45
@dienteperro I don't know how you did when you converted the MySQL tables. If you really want to try it out with the correct way of converting the tables, please use the Nextcloud VM install script on a CLEAN Ubuntu 16.04 Server VM. 
Info: https://github.com/nextcloud/vm/blob/master/README.md#build-requirements '
File: https://raw.githubusercontent.com/nextcloud/vm/master/nextcloud_install_production.sh

**Comment by dienteperro** [comment] 2017-02-06 15:51
I think is due to have a more inclusive user base, the usual lamp extended user base.On Feb 6, 2017 10:12 AM, Loïc Blot <notifications@github.com> wrote:i don't know why they doesn't support pgsql as it has a stronger SGBD, unlike mysql (look at this UTF8 crap...)

**Comment by enoch85** [comment] 2017-02-06 17:23
>I think is due to have a more inclusive user base, the usual lamp extended user base

@dienteperro What do you mean?

**Comment by dienteperro** [comment] 2017-02-06 19:38
There are lot of people/hostings out there that uses PHP+MySQL and havent use/know pgsql. Not referring to the team of nc of course. This could be a larger probable user/contributor base to start with. Just ideas Im not in shoes of nc ;-)On Feb 6, 2017 12:23 PM, Daniel Hansson <notifications@github.com> wrote:
I think is due to have a more inclusive user base, the usual lamp extended user base

@dienteperro What do you mean?

**Comment by nerzhul** [comment] 2017-02-06 19:39
yeah in understand well @dienteperro but the problem is MySQL and Emojis, this show many limitations :(

**Comment by dienteperro** [comment] 2017-02-06 19:46
@nerzhul You got me! definitely will give a try to nginx+pgsql in the next days! ;-D I also use an application (Nuxeo) that uses MongoDB for docs db store, trying to surpass pgsql limitations on scale out of documents... Mhhmm... could this be an interesting feature for Nextcloud in the future @enoch85 ?

**Comment by nerzhul** [comment] 2017-02-06 19:48
@dienteperro nginx or apache is not the problem here, i'm using apache 2.4 without problems :) it's just taste. Mongodb is purely shit, just a developper crazy thing, not an infrastructure thing, it's slow, and mongodb will use postgresql json backend because it's faster than their json backend... lol

**Comment by dienteperro** [comment] 2017-02-06 19:51
No MongoDB then, LOL!

**Comment by enoch85** [comment] 2017-02-06 20:18
>  it's just slow

Nuff said.
