### ISSUE TITLE
Synchronization error (impossible)

### ISSUE THREAD

**Issue by pci06** [nextcloud/ocsms#165] opened 2017-01-23 21:03 UTC
Doctrine\DBAL\Exception\DriverException: An exception occurred while executing 'INSERT INTO oc_ocsms_smsdatas (user_id, added, lastmodified, sms_flags, sms_date, sms_id,sms_address, sms_msg, sms_mailbox, sms_type) VALUES (?,?,?,?,?,?,?,?,?,?)' with params ["pierre", "2017-01-23 20:47:54", "2017-01-23 20:47:54", "11", "1483619299547", 14615, "+00123456789", "Oui et toi \ud83d\ude0a", 0, 1]: SQLSTATE[HY000]: General error: 1366 Incorrect string value: '\xF0\x9F\x98\x8A' for column 'sms_msg' at row 1

### Steps to reproduce
1. Buy android app
2. Create a new account
3. Try to sync :)
3.

### Expected behaviour
Sync in nextcloud sms app (activated)

### Actual behaviour
Does'nt work at all

### Server configuration

**NextCloud/ownCloud version:**
Nextcloud 11.0.1 (stable)
**PHP version:**
Version: 7.0.13
Memory Limit: 128.0 MB
Max Execution Time: 3600
Upload max size:
**HTTPd server:**
apache2
**HTTPS:**
apache2

mysql  Ver 14.14 Distrib 5.7.16, for Linux (x86_64) using  EditLine wrapper

### Client configuration

**Android version:**
5.1.1
**Phone:**
GS5 mini
**ownCloud SMS app version:**
0.24.0
### Logs
logcat said unhandled error

apache2 said 500 internal server error

nextcloud see log extract above

**Comment by nerzhul** [comment] 2017-01-24 09:08
It's an UTF8 problem, i did a related message in app repo:

> I looked at the whole nextcloud source code to understand how this can be fixed.
> 
> Please add 'mysql.utf8mb4' => true, to your config.php
> 
> See: https://github.com/nextcloud/server/blob/33ca69166a41188a6e19849243c5e1c2a16860dc/config/config.sample.php#L1243
> 
> You may need to alter your MySQL tables after this, like mentioned in @enoch85 article:
> 
> ALTER TABLE table_name CONVERT TO CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
> 
> Or just use a real SQL engine, pgsql (joke)
> 
> Please tell me if that fixes your problem

**Comment by pci06** [comment] 2017-01-24 18:24
Or a better type for the column:
ALTER TABLE oc_ocsms_smsdatas MODIFY sms_msg TEXT;

This fix the problem and now I have a bunch of sms in my nextcloud instance.

Overall it would ease, in nextcloud sms app, a mysql text search query with this type, like we say in french: "je dis ça, je dis rien" ;-)

Thx.

**Comment by pci06** [comment] 2017-01-24 19:56
Still have the problem with my solution and your's...
Looking arround to see if there's a *nice* way to convert (or filter [worst]) this type of string.

**Comment by pci06** [comment] 2017-01-24 21:50
I'm actually trying to follow the encoding "path" of a sms_msg string.
I'm actually looking at the connection charset between the client (OCP:DB/mysql) and the server (mysql).

[test_encoding.txt](https://github.com/nextcloud/ocsms/files/728038/test_encoding.txt)

The table encoding_test is using utf8_bin :)

**Comment by FrederikLauber** [comment] 2017-01-25 22:37
The problem is that utf8_bin in mysql is still only 3 bytes but the symbol you want to put in is 4 bytes long.
This has been fixed in mysql from version 5.5 onwards with the illnamed utf8mb4 encoding which is actual proper utf8 and not a 3 byte subset.

**Comment by nerzhul** [comment] 2017-01-26 06:52
it seems next nextcloud version will change the default encoding in MySQL databases

**Comment by FrederikLauber** [comment] 2017-01-26 08:39
Good, but the problem is with the MySQL server itself. Anyone running MySQL < 5.5 (like me :( ) cannot fix this... But that is my problem, not yours.

**Comment by nerzhul** [comment] 2017-01-26 13:44
Problem should be solved upstream by next nextcloud upgrade.

**Closed by nerzhul** 2017-01-26 13:44 UTC
