### ISSUE TITLE
Compatibility with Nextcloud 20

### ISSUE THREAD

**Issue by YamiYukiSenpai** [nextcloud/ocsms#328] opened 2020-12-23 11:18 UTC
On the website, it says that version 19 and lower is required to use it.

**Comment by e-alfred** [comment] 2020-12-24 15:49
Duplicate of https://github.com/nextcloud/ocsms/issues/327. @nerzhul uploaded the new release to the App Store.

**Closed by e-alfred** 2020-12-24 15:49 UTC
